version: "3"

services:
  elasticsearch:
    image: elasticsearch:6.5.0
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      nofile:
         soft: 65536
         hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
#    volumes:
#      - esdata

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
#    volumes:
#      - mongo

  #backend:
  #  depends_on:
  #    - mongo
  #  image: backend
  #  ports:
  #    - 3000:3000


#volumes:
#  esdata:
#
#  mongo: